export const skills = [
  { name: "Languages", description: "Russian, English, Japanese" },
  { name: "Development", description: "OOP, TDD, vim, vscode" },
  { name: "Web", description: "Django, DRF, Vue 2/3, Vuex, Pinia, Bootstrap 5, Vuetify, sass." },
  { name: "Python", description: "numpy, pandas, matplotlib" },
  {
    name: "General",
    description:
      "GNU/Linux (ubuntu, debian, fedora, arch), bash, libvirt, virt-manager, VirtualBox, Docker",
  },
  {
    name: "3d",
    description:
      "Blender, AutoCAD, Unity3D render pipelines, PBR in general, hard-surface modelling, non-destructive modelling",
  },
];

export const projects = [
  {
    name: "EMTK",
    description:
      "Blender addon, designed to simplify editing modifiers stack through modal operators and abstraction layers.",
    year: "2021-2022",
    image: "screenshot_emtk.jpg",
    link_gh: "https://github.com/0djentd/emtk",
    link_site: "",
    link_yt: "",
    type: "addon",
    stack: [
      "python",
      "blender",
      "json",
      "oop",
      "ui",
      "3d",
      "logging",
      "regex",
      "libemtk",
    ],
  },
  {
    name: "Alprou",
    description: "Website for managing your routines.",
    year: "2022",
    image: "screenshot_alprou.png",
    link_gh: "https://github.com/0djentd/alprou",
    link_site: "https://0djentd.pythonanywhere.com/",
    link_yt: "",
    type: "website",
    stack: ["vue", "rest", "api", "html", "css", "js", "sass", "npm", "vuex"],
  },
  {
    name: "Alprou (backend)",
    description: "Website for managing your routines. (backend)",
    year: "2022",
    image: "screenshot_alprou_backend.png",
    link_gh: "https://github.com/0djentd/alprou-backend",
    link_site: "https://0djentd.pythonanywhere.com/",
    link_yt: "",
    type: "website",
    stack: ["django", "rest", "api"],
  },
  {
    name: "Portfolio",
    description: "This website.",
    year: "2022",
    image: "screenshot_portfolio.png",
    link_gh: "https://github.com/0djentd/portfolio",
    link_site: "/portfolio/",
    link_yt: "",
    type: "website",
    stack: ["vue", "html", "css", "js", "ts", "npm", "pinia"],
  },
  {
    name: "libemtk",
    description:
      "Python library for Blender, designed to bring new level of abstraction to modifiers stack.",
    year: "2021",
    image: "screenshot_libemtk.png",
    link_gh: "https://github.com/0djentd/libemtk",
    link_site: "",
    link_yt: "",
    type: "library",
    stack: [
      "python",
      "blender",
      "unittest",
      "json",
      "oop",
      "3d",
      "logging",
      "regex",
    ],
  },
  {
    name: "modal_shortcuts",
    description:
      "Keyboard shortcuts and other utility for modal operators in Blender",
    year: "2021",
    image: "",
    link_gh: "https://github.com/0djentd/modal_shortcuts",
    link_site: "",
    link_yt: "",
    type: "library",
    stack: ["python", "ui", "blender", "json", "oop", "3d"],
  },
  {
    name: "class_variables_editor_ui",
    description: "UI for editing python's class variables in Blender",
    year: "2021",
    image: "screenshot_class_variables_editor_ui.png",
    link_gh: "https://github.com/0djentd/class_variables_editor_ui",
    link_site: "",
    link_yt: "",
    type: "library",
    stack: ["python", "ui", "blender", "oop", "regex"],
  },
  {
    name: "Other projects",
    description: "My github repositories",
    year: "2019-2022",
    image: "",
    link_gh: "https://github.com/0djentd?tab=repositories",
    link_site: "",
    link_yt: "",
    type: "",
    stack: ["python", "html", "js", "css", "vue", "oop", "api", "script", "logging", "regex"],
  },
];
