export const projects = [
  {
    name: "EMTK",
    description:
      "Blender addon, designed to simplify editing modifiers stack through modal operators and abstraction layers.",
    year: "2021-2022",
    image: "screenshot3.jpg",
    link_gh: "https://github.com/0djentd/emtk",
    link_site: "",
    link_yt: "",
    type: "addon",
    stack: [
      "python",
      "blender",
      "json",
      "oop",
      "ui",
      "3d",
      "logging",
      "regex",
      "libemtk",
    ],
  },
  {
    name: "libemtk",
    description:
      "Python library for Blender, designed to bring new level of abstraction to modifiers stack.",
    year: "2021",
    image: "",
    link_gh: "https://github.com/0djentd/libemtk",
    link_site: "",
    link_yt: "",
    type: "library",
    stack: [
      "python",
      "blender",
      "unittest",
      "json",
      "oop",
      "3d",
      "logging",
      "regex",
    ],
  },
  {
    name: "modal_shortcuts",
    description:
      "Keyboard shortcuts and other utility for modal operators in Blender",
    year: "2021",
    image: "",
    link_gh: "https://github.com/0djentd/modal_shortcuts",
    link_site: "",
    link_yt: "",
    type: "library",
    stack: ["python", "ui", "blender", "json", "oop", "3d"],
  },
  {
    name: "class_variables_editor_ui",
    description: "UI for editing python's class variables in Blender",
    year: "2021",
    image: "",
    link_gh: "https://github.com/0djentd/class_variables_editor_ui",
    link_site: "",
    link_yt: "",
    type: "library",
    stack: ["python", "ui", "blender", "oop", "regex"],
  },
  {
    name: "Alprou",
    description: "Website for managing your routines. (WIP)",
    year: "2022",
    image: "",
    link_gh: "",
    link_site: "",
    link_yt: "",
    type: "website",
    stack: [
      "django",
      "vue",
      "rest",
      "api",
      "html",
      "css",
      "js",
      "sass",
      "npm",
      "pinia",
    ],
  },
  {
    name: "Portfolio",
    description: "This website.",
    year: "2022",
    image: "",
    link_gh: "https://github.com/0djentd/portfolio",
    link_site: "/portfolio/",
    link_yt: "",
    type: "website",
    stack: ["vue", "html", "css", "js", "ts", "npm", "pinia"],
  },
];
